//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class episodes
    {
        public int ID { get; set; }
        public int Serial { get; set; }
        public int Season { get; set; }
        public int No { get; set; }
        public string Title { get; set; }
        public short Seen { get; set; }
    }
}
