//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class series
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public int PublicS { get; set; }
        public int Seen { get; set; }
    }
}
